scrape_configs:
  - job_name: 'scrapper'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8091
  - job_name: 'bot'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8081

