app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  bot_base_url: http://localhost:8080/

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5437/scrapper
    username: postgres
    password: postgres


server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml


springdoc:
  swagger-ui:
    path: /swagger-ui
