app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-base-url: http://localhost:8090/
  retry-max-attempts: 2
  retry-delay: 100

spring:
  application:
    name: bot, scrapper
  jackson:
    time-zone: UTC
  kafka:
    bootstrap-servers: localhost:29092
  docker:
    compose:
      enabled: true
      file: compose.yml

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: ["info", "health", "prometheus"]
      path-mapping:
        prometheus: metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
  metrics.tags:
    application: ${spring.application.name}

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
