app:
  telegram-token: ${TELEGRAM_TOKEN}
  scheduler:
    interval: 15000
  github_base_url: https://api.github.com
  stackof_base_url: https://api.stackexchange.com

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

